### ISSUE TITLE
Regex in zend-expressive-zendrouter

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-laminasrouter#1]
Hello,
we will migrate our ZF2 MVC Application to ZF3 Expressive. For some functions we use Regex to build the routes. When can I use Regex in zend-expressive-zendrouter?

For example:

```php
'vcalendar' => [
  'type' => 'regex',
  'options' => [
    'regex' => '/vcalendar/(?<room>[0-9]+)(\.(?<format>(html|ics)))?',
    'defaults' => [
      'action' => 'vcalendar',
      'format' => 'ics'
    ],
    'spec' => '/vcalendar/%room%.%format%',
  ],
],
```

---

Originally posted by @mano87 at https://github.com/zendframework/zend-expressive-zendrouter/issues/22

**Comment by weierophinney** [comment]
You can't, at least not using the Expressive API for attaching routes to middleware, due to a need to keep the API compatible between all routing implementations. In particular, we found that HTTP method negotiation, while supported directly in other routing implementations, was something we had to "hack" around to make work with zend-router; we ended up injecting a `method` route as a child route on the primary route to make it happen.

We could potentially support this by allowing you to provide the route type via route options (which would be handled in the `ZendRouter::injectRoute()` method); if anybody would like to try their hand at this, I'd welcome a pull request.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-expressive-zendrouter/issues/22#issuecomment-283497032

**Comment by Ocramius** [comment]
Closing this: no work planned, unless PRs come up.
