### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by agustingomes** [mezzio/mezzio-laminasrouter#10]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Provide PHP 8.1 support. Once this is achieved, it should unblock https://github.com/mezzio/mezzio/issues/95

**Comment by froschdesign** [comment]
[laminas-router already supports PHP 8.1.](https://github.com/laminas/laminas-router/releases/tag/3.5.0) and we can drop version 7.3 of PHP here.

**Comment by froschdesign** [comment]
@agustingomes 
Please see #9

**Comment by Ocramius** [comment]
Handled in #9
